%YAML:1.0

K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [299.4659, 0, 339.2976, 0, 299.3240, 240.4935, 0, 0, 1]
d: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [-0.29287, 0.08532, 0.0002695, -0.0002297, 0]

Camera.width: 636
Camera.height: 480

grid_length: 0.15
corner_in_x: 7
corner_in_y: 5
