%YAML:1.0

K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [300.1157, 0, 320.7811,0, 300.0367, 240.0736,0, 0, 1]
d: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [-0.26497, 0.05619, -0.0009188, -0.0008721, 0]

Camera.width: 636
Camera.height: 480

grid_length: 0.15
corner_in_x: 7
corner_in_y: 5
